### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by dancreppel** [dancreppel/FoG#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
Works great! I'll meet with you later to discuss styling.

**Comment by dancreppel** [comment]
Fixed font
